### ISSUE TITLE
Discord Invite Closed?

### ISSUE THREAD

**Issue by iSeeEthan** [SoDOff-Project/sodoff#1]
I would love to play the game but I can’t join the discord because invites are paused. There is no other way to ask y’all about this besides here.

**Comment by MeAlam1** [comment]
https://discord.gg/6wHAFeeXdn
Here ya go

**Comment by Drachenbauer** [comment]
This link also does not work

**Comment by MeAlam1** [comment]
> This link also does not work

I see SoDOff is closing invites, sadly i wont be able to help then since i did generate my Invite as Infinite
